#namespace
apiVersion: v1
kind: Namespace
metadata:
  name: kubealerta

---
#serviceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubealerta-sa
  namespace: kubealerta

---
#clusterrole
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubealerta-clusterrole
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]

---
#cluster role binding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubealerta-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: kubealerta-sa
  namespace: kubealerta
roleRef:
  kind: ClusterRole
  name: kubealerta-clusterrole
  apiGroup: rbac.authorization.k8s.io


---
# application deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubealerta
  namespace: kubealerta
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubealerta
  template:
    metadata:
      labels:
        app: kubealerta
    spec:
      serviceAccountName: kubealerta-sa
      containers:
        - name: kubealerta-container
          image: saisk026/kubealerta:1.2
          ports:
            - containerPort: 5000

---
#CRD for notification webhook URL
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: notifies.kubealerta.io
spec:
  group: kubealerta.io
  names:
    kind: Notify
    plural: notifies
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required: ["spec"]
          properties:
            spec:
              type: object
              required: ["webhookURL"]
              properties:
                webhookURL:
                  type: string

---
# filtering resources at Namespace level
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: nsfilters.kubealerta.io
spec:
  group: kubealerta.io
  names:
    kind: NamespacedFilter
    plural: nsfilters
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required: ["spec"]
          properties:
            spec:
              type: object
              properties:
                resource:
                  type: string
                  required: ["resource","rNames","namespaces"]
                  enum:
                    - Deployment
                    - StatefulSet
                    - Pod
                rNames:
                  type: array
                  items:
                    type: string
                namespaces:
                  type: array
                  items:
                    type: string

---
# filtering resources at cluster level
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clfilters.kubealerta.io
spec:
  group: kubealerta.io
  names:
    kind: ClusterFilter
    plural: clfilters
  scope: Cluster
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required: ["spec"]
          properties:
            spec:
              type: object
              required: ["nodesNames", "resource"]
              properties:
                resource:
                  type: string
                  enum:
                    - Nodes
                nodesNames:
                  type: array
                  items:
                    type: string

